// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisagramAPI.Models;

namespace VisagramAPI.Migrations
{
    [DbContext(typeof(VisagramDbContext))]
    [Migration("20211206214047_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("VisagramAPI.Models.SalaryDetails", b =>
                {
                    b.Property<long>("SalaryDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<int>("SalaryOfferId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalaryOfferValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SalaryPaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("SalaryDetailsId");

                    b.HasIndex("SalaryOfferId");

                    b.HasIndex("SalaryPaymentId");

                    b.ToTable("SalaryDetails");
                });

            modelBuilder.Entity("VisagramAPI.Models.SalaryOffer", b =>
                {
                    b.Property<int>("SalaryOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("OfferName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OfferValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalaryOfferId");

                    b.ToTable("SalaryOffers");
                });

            modelBuilder.Entity("VisagramAPI.Models.SalaryPayment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("PaymentNumber")
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("StaffId");

                    b.ToTable("SalaryPayments");
                });

            modelBuilder.Entity("VisagramAPI.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StaffSurname")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("VisagramAPI.Models.SalaryDetails", b =>
                {
                    b.HasOne("VisagramAPI.Models.SalaryOffer", "SalaryOffer")
                        .WithMany()
                        .HasForeignKey("SalaryOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisagramAPI.Models.SalaryPayment", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("SalaryPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryOffer");
                });

            modelBuilder.Entity("VisagramAPI.Models.SalaryPayment", b =>
                {
                    b.HasOne("VisagramAPI.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("VisagramAPI.Models.SalaryPayment", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
